[package]
name = "life"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
crossterm = { workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
